import type { PlaybackState, SessionViewMode } from "../../types/recall";
import type { SessionNote, TimelineItem } from "../../types/timeline";
import { formatProducerMoment } from "../../utils/producerEvents";

// Generates an export-ready markdown document from the curated timeline.
// Reflects user edits and excludes hidden items — the raw event stream is not used directly.

export function buildMarkdownDocument(
  items: TimelineItem[],
  freeNotes: SessionNote[],
  playback: PlaybackState,
  viewMode: SessionViewMode,
): string {
  const lines: string[] = [];
  const tempoRange = deriveTempoRange(items, playback);
  const sessionLabel = viewMode === "live" ? "Live Capture" : "Saved Session";
  const now = new Date().toLocaleDateString(undefined, {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  lines.push(`# Session Notes — ${sessionLabel}`);
  lines.push("");

  const headerParts: string[] = [`**Date:** ${now}`];
  if (playback.projectClock) headerParts.push(`**Duration:** ${playback.projectClock}`);
  if (tempoRange) headerParts.push(`**Tempo:** ${tempoRange}`);
  if (items.length > 0) headerParts.push(`**${items.length} moment${items.length === 1 ? "" : "s"}**`);
  lines.push(headerParts.join(" · "));
  lines.push("");
  lines.push("---");
  lines.push("");

  if (items.length === 0) {
    lines.push("*No moments captured yet.*");
    lines.push("");
  } else {
    lines.push("## Timeline");
    lines.push("");

    for (const item of items) {
      const p = formatProducerMoment(item.raw);
      const title = item.edits.title ?? p.title;
      const detail = item.edits.description ?? p.detail;
      const context =
        p.contextLabel && p.contextLabel !== "Ableton" && p.contextLabel !== "Max_for_Live"
          ? ` — ${p.contextLabel}`
          : "";

      lines.push(`\`${item.raw.sessionTimecode}\` **${title}**${context}`);

      if (detail) {
        lines.push(`  *${detail}*`);
      }

      for (const note of item.notes) {
        lines.push(`> 📝 ${note.text}`);
      }

      if (detail || item.notes.length > 0) {
        lines.push("");
      }
    }

    lines.push("---");
    lines.push("");
  }

  if (freeNotes.length > 0) {
    lines.push("## Session Notes");
    lines.push("");

    for (const note of freeNotes) {
      lines.push(`- \`${note.sessionTimecode}\` ${note.text}`);
    }

    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push(
    `*Generated by Recall Studio · ${items.length} moment${items.length === 1 ? "" : "s"} captured*`,
  );

  return lines.join("\n");
}

export function deriveTempoRange(
  items: TimelineItem[],
  playback: PlaybackState,
): string | null {
  const tempos = items
    .filter((i) => i.raw.type === "tempo")
    .flatMap((i) => {
      const bpm = i.raw.metadata?.bpm;
      const prev = i.raw.metadata?.previousBpm;
      return [
        typeof bpm === "number" ? bpm : null,
        typeof prev === "number" ? prev : null,
      ].filter((v): v is number => v !== null);
    });

  if (tempos.length === 0 && typeof playback.tempo === "number") {
    return `${formatBpm(playback.tempo)} BPM`;
  }

  if (tempos.length === 0) return null;

  const allTempos = typeof playback.tempo === "number" ? [...tempos, playback.tempo] : tempos;
  const min = Math.min(...allTempos);
  const max = Math.max(...allTempos);

  return min === max ? `${formatBpm(min)} BPM` : `${formatBpm(min)}–${formatBpm(max)} BPM`;
}

function formatBpm(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}
